import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

/**
 * The Codex review is the merge gate, and its prompt used to name no diff
 * boundary at all, so the model picked one per run: #94 chose `origin/dev` and
 * reviewed its three files, #87 chose "an empty base snapshot" and blocked on a
 * workflow file it does not touch, and #90 blocked on a `gateway.ts` clamp that
 * #89 had already merged. Nothing failed loudly — the job stayed green and the
 * PR simply never merged, with a plausible-looking finding attached.
 *
 * So these are text assertions against the workflow rather than a run of it:
 * the failure is a missing instruction, which no green run can reveal, and the
 * step needs a real `refs/pull/N/merge` checkout to execute at all.
 */

// Git may materialize the tracked workflow with CRLF on Windows. The assertions
// inspect YAML structure, not checkout line-ending policy, so normalize once at
// the boundary and keep the section matcher deterministic on every platform.
const workflow = readFileSync('.github/workflows/codex-review.yml', 'utf8').replace(/\r\n/g, '\n')
const prompt = readFileSync('.github/codex/prompts/review.md', 'utf8')

/** Slice from `heading` to the next sibling at the same indent, or '' if absent. */
function section(text, heading, nextPattern) {
  const start = text.indexOf(heading)
  if (start === -1) return ''
  const next = text.slice(start + heading.length).search(nextPattern)
  return next === -1 ? text.slice(start) : text.slice(start, start + heading.length + next)
}

const reviewJob = section(workflow, '\n  review:\n', /\n {2}auto-merge:\n/)
const autoMergeJob = section(workflow, '\n  auto-merge:\n', /\n {2}[a-zA-Z0-9_-]+:\n/)
const scopeStep = section(
  reviewJob,
  '- name: Copy trusted review prompt and pin the diff scope',
  /\n {6}- name:/,
)

describe('codex review diff scope', () => {
  it('pins the scope in a step of its own, inside the review job', () => {
    // Named first so a rename shows up as this assertion rather than as every
    // other one collapsing at once.
    expect(reviewJob).not.toBe('')
    expect(scopeStep).not.toBe('')
  })

  it('hands the review a generated diff instead of a base to guess at', () => {
    expect(scopeStep).toContain('.codex-review-diff.patch')
    expect(scopeStep).toContain('.codex-review-files.txt')
    expect(scopeStep).toMatch(/git diff "\$base_sha" "\$head_sha"/)
    expect(scopeStep).toMatch(/git diff --name-status "\$base_sha" "\$head_sha"/)
  })

  it('derives the boundary from the merge commit under review', () => {
    // Not from a branch name: `main` trails `dev` by the whole backlog, so a
    // ref-name comparison hands the review 78 commits of other people's work.
    expect(scopeStep).toMatch(/base_sha="\$\(git merge-base HEAD\^1 HEAD\^2\)"/)
    expect(scopeStep).toMatch(/head_sha="\$\(git rev-parse HEAD\^2\)"/)
    expect(scopeStep).not.toMatch(/git diff\s+\S*origin\/(main|dev)/)
    expect(scopeStep).not.toMatch(/git (diff|merge-base)[^\n]*\$BASE_REF/)
  })

  it('refuses to build a scope from a tree that is not a merge result', () => {
    // `HEAD^1` and `HEAD^2` silently mean nothing on a non-merge checkout, and
    // an empty diff reads to the model as "this PR changes nothing".
    expect(scopeStep).toMatch(/git rev-parse --verify --quiet HEAD\^2/)
    expect(scopeStep).toContain('exit 1')
  })

  it('tells the review that everything before the base is out of scope', () => {
    expect(scopeStep).toContain('## Diff scope (generated by CI, authoritative)')
    expect(scopeStep).toMatch(/do not diff against/i)
    expect(scopeStep).toMatch(/pre-existing/i)
    expect(scopeStep).toMatch(/out of scope/i)
  })

  it('expands the heredoc so the SHAs reach the prompt as values', () => {
    // A quoted `<<'EOF'` would ship `$base_sha` to the model literally, which
    // is worse than the original bug: an instruction that looks authoritative
    // and names nothing.
    expect(scopeStep).toContain('<<EOF')
    expect(scopeStep).not.toContain("<<'EOF'")
    expect(scopeStep).toMatch(/git diff \$base_sha \$head_sha/)
  })

  it('runs before the review, on the prompt the review is actually given', () => {
    const scopeAt = reviewJob.indexOf('pin the diff scope')
    const codexAt = reviewJob.indexOf('- name: Run Codex review')
    expect(scopeAt).toBeGreaterThan(-1)
    expect(codexAt).toBeGreaterThan(scopeAt)
    // Pointing `prompt-file` back at `trusted-base` would drop the appended
    // scope without failing anything.
    const promptFiles = [...reviewJob.matchAll(/prompt-file: (.+)/g)].map((m) => m[1].trim())
    expect(promptFiles.length).toBeGreaterThanOrEqual(2)
    for (const file of promptFiles) {
      expect(file).toBe('${{ github.workspace }}/.codex-review-prompt.md')
    }
  })

  it('keeps pull-request-authored text out of the prompt', () => {
    // The `trusted-base` checkout exists so a PR cannot rewrite the prompt that
    // judges it. The diff and the path list are PR-authored, so they go to disk
    // and the prompt names their paths; only the number and the base ref are
    // interpolated, and both are shape-checked first.
    expect(scopeStep).not.toMatch(/github\.event\.pull_request/)
    expect(scopeStep).toMatch(/printf '%s' "\$PR_NUMBER" \| grep -Eq '\^\[0-9\]/)
    expect(scopeStep).toMatch(/printf '%s' "\$BASE_REF" \| grep -Eq/)
    const envKeys = [...scopeStep.matchAll(/^ {10}([A-Z_]+):/gm)].map((m) => m[1])
    expect(envKeys.sort()).toEqual(['BASE_REF', 'PR_NUMBER'])
  })

  it('stops the prompt describing main as the branch to compare against', () => {
    expect(prompt).not.toContain('`main` is the stable branch.')
    expect(prompt).toMatch(/`dev` is the integration branch/)
    expect(prompt).toMatch(/trails `dev`/)
    expect(prompt).toMatch(/Diff scope/)
  })
})

describe('codex review auto-merge gate', () => {
  it('uses bracket notation for job and output ids that contain hyphens', () => {
    expect(autoMergeJob).not.toBe('')
    expect(autoMergeJob).toContain("needs['review-verdict'].outputs.verdict == 'PASS'")
    expect(autoMergeJob).toContain("needs['review-verdict'].outputs['eligible-for-auto-merge'] == 'true'")
    expect(autoMergeJob).toContain("needs['resolve-pr'].outputs['base-ref'] == 'dev'")
    expect(autoMergeJob).not.toContain('needs.review-verdict')
    expect(autoMergeJob).not.toContain('outputs.eligible-for-auto-merge')
  })
})
